### PR TITLE
feat: add live map page with drivers

### PR DESCRIPTION
**Pull request by nidalhjab**

### CODE REVIEW

**Review by marwank7 — COMMENTED** [review]
Did you make it that when the user presses cancel on the go to fav locations modal be redirected to live map?

**Comment by nidalhjab** [comment]
> Did you make it that when the user presses cancel on the go to fav locations modal be redirected to live map?

**Comment by marwank7** [comment]
> > Did you make it that when the user presses cancel on the go to fav locations modal be redirected to live map?
> 
> which cancel? it's just about the live map page with drivers

The first modal that prompts the user to choose between getting redirected to favourite location or cancel, the cancel should redirect the user to the live map since its basically the main page

**Comment by nidalhjab** [comment]
> > > Did you make it that when the user presses cancel on the go to fav locations modal be redirected to live map?
> > 
> > 
> > which cancel? it's just about the live map page with drivers
> 
> The first modal that prompts the user to choose between getting redirected to favourite location or cancel, the cancel should redirect the user to the live map since its basically the main page

> Fixed

**Review by marwank7 — APPROVED** [review]

**Pull request merged**
